# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9610bb9e2840c64d3f26ee1e78cdba4c1d0c04259629b4ea75b11655df450d4b6d5b8601e55b3dea50351fd28a7cf68b21278b1ca24d97679f004e7e2229919c

test:
  secret_key_base: b65bc40578af3782d630feb9abfb601db97a07268c687df5bdf71d2711e7e7e4ea2718fb60ef1af0c34918be9f8379ff0de5ed91b244a38aa389a5b7c59c1f6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
